### ISSUE TITLE
Semaphore webhook causes exception

### ISSUE THREAD

**Issue by jwilf** [pivotal/projectmonitor#67]
When posting a webhook from Semaphore we get errors like this:

2015-01-14_10:55:23.68437 Started POST "/projects/632dcb4d-7ed0-4860-b4c8-77428272d5e3/status" for 127.0.0.1 at 2015-01-14 11:55:23 +0100
2015-01-14_10:55:28.82517
2015-01-14_10:55:28.82521 NoMethodError (undefined method `key?' for ["branch_name", "master"]:Array):
2015-01-14_10:55:28.82522   lib/payload/semaphore_payload.rb:47:in `extract_builds_if_build_history_url'
2015-01-14_10:55:28.82523   lib/payload/semaphore_payload.rb:24:in `convert_webhook_content!'
2015-01-14_10:55:28.82524   lib/payload.rb:26:in `webhook_status_content='
2015-01-14_10:55:28.82525   app/controllers/status_controller.rb:11:in `create'
2015-01-14_10:55:28.82526
2015-01-14_10:55:28.82526

And the status of our Semaphore projects is not updated.

**Comment by tjgrathwell** [comment]
Should be fixed by #69
