### ISSUE TITLE
Can't configure tracker integration

### ISSUE THREAD

**Issue by vsanta** [pivotal/projectmonitor#70]
Maybe we're doing something wrong but we're getting 404 on the validation.

Note: I changed my API after this screenshot :)
![screen shot 2015-01-20 at 4 16 42 pm](https://cloud.githubusercontent.com/assets/23849/5826333/fc7e6bfa-a0bf-11e4-8637-cb91652615c2.png)

**Comment by alexdown** [comment]
Slightly different error here. On the browser console, I see all calls returns a 202, not a 404.
Those calls are not to a pivotal tracker address, but to the current app (the project monitor app itself).

When I look at the app logs, I see:

```
2015-04-23T07:27:38.371609+00:00 heroku[router]: at=info method=POST path="/projects/validate_tracker_project" host=<APP_NAME_HERE>.herokuapp.com request_id=8bb12914-048a-4895-9205-08afbc8cf9e4 fwd="27.110.79.215" dyno=web.1 connect=2ms service=75ms status=404 bytes=967
2015-04-23T07:27:38.295931+00:00 app[web.1]: Started POST "/projects/validate_tracker_project" for 27.110.79.215 at 2015-04-23 07:27:38 +0000
2015-04-23T07:27:38.367793+00:00 app[web.1]: 
2015-04-23T07:27:38.367799+00:00 app[web.1]: ActiveRecord::RecordNotFound (Couldn't find Project without an ID):
2015-04-23T07:27:38.367801+00:00 app[web.1]:   app/controllers/projects_controller.rb:95:in `validate_tracker_project'
2015-04-23T07:27:38.367802+00:00 app[web.1]:   app/controllers/projects_controller.rb:121:in `scope_by_aggregate_project'
2015-04-23T07:27:38.367804+00:00 app[web.1]: 
2015-04-23T07:27:38.367805+00:00 app[web.1]:
```

Seems it can't find the project.. but the request contains the `id`, and the project monitor db a project with that id.

One question: is it correct that the call is to a route in the same projectmonitor app instance? I see that the route is defined in `routes.rb`:

```ruby
  post 'projects/validate_tracker_project'
```

but -being not familiar with ruby at all- I can't see in the code where the call to the actual pivotal tracker url is made... if I make a POST to http://pulse.pivotallabs.com/projects/validate_tracker_project (the URL in your screenshot) I just get a login page... my pivotal tracker login doesn't work.
